//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustStay.Web.ATRCServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ATRCProfile", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class ATRCProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ATRCIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATRCNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATRCNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ATRCTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmenitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmenitiesNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuisinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuisinesNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiningEndsOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiningFacilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiningFacilityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> DiningFromTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiningStartsOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> DiningToTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeoLocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HighlightNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewAmenitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileImageNewNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RatingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RestChairProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string highlightsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ATRCId {
            get {
                return this.ATRCIdField;
            }
            set {
                if ((this.ATRCIdField.Equals(value) != true)) {
                    this.ATRCIdField = value;
                    this.RaisePropertyChanged("ATRCId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATRCName {
            get {
                return this.ATRCNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ATRCNameField, value) != true)) {
                    this.ATRCNameField = value;
                    this.RaisePropertyChanged("ATRCName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATRCNumber {
            get {
                return this.ATRCNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ATRCNumberField, value) != true)) {
                    this.ATRCNumberField = value;
                    this.RaisePropertyChanged("ATRCNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ATRCTypeId {
            get {
                return this.ATRCTypeIdField;
            }
            set {
                if ((this.ATRCTypeIdField.Equals(value) != true)) {
                    this.ATRCTypeIdField = value;
                    this.RaisePropertyChanged("ATRCTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amenities {
            get {
                return this.AmenitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.AmenitiesField, value) != true)) {
                    this.AmenitiesField = value;
                    this.RaisePropertyChanged("Amenities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmenitiesNames {
            get {
                return this.AmenitiesNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.AmenitiesNamesField, value) != true)) {
                    this.AmenitiesNamesField = value;
                    this.RaisePropertyChanged("AmenitiesNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryNames {
            get {
                return this.CategoryNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNamesField, value) != true)) {
                    this.CategoryNamesField = value;
                    this.RaisePropertyChanged("CategoryNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuisines {
            get {
                return this.CuisinesField;
            }
            set {
                if ((object.ReferenceEquals(this.CuisinesField, value) != true)) {
                    this.CuisinesField = value;
                    this.RaisePropertyChanged("Cuisines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuisinesNames {
            get {
                return this.CuisinesNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.CuisinesNamesField, value) != true)) {
                    this.CuisinesNamesField = value;
                    this.RaisePropertyChanged("CuisinesNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiningEndsOn {
            get {
                return this.DiningEndsOnField;
            }
            set {
                if ((object.ReferenceEquals(this.DiningEndsOnField, value) != true)) {
                    this.DiningEndsOnField = value;
                    this.RaisePropertyChanged("DiningEndsOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiningFacility {
            get {
                return this.DiningFacilityField;
            }
            set {
                if ((this.DiningFacilityField.Equals(value) != true)) {
                    this.DiningFacilityField = value;
                    this.RaisePropertyChanged("DiningFacility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiningFacilityName {
            get {
                return this.DiningFacilityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DiningFacilityNameField, value) != true)) {
                    this.DiningFacilityNameField = value;
                    this.RaisePropertyChanged("DiningFacilityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> DiningFromTime {
            get {
                return this.DiningFromTimeField;
            }
            set {
                if ((this.DiningFromTimeField.Equals(value) != true)) {
                    this.DiningFromTimeField = value;
                    this.RaisePropertyChanged("DiningFromTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiningStartsOn {
            get {
                return this.DiningStartsOnField;
            }
            set {
                if ((object.ReferenceEquals(this.DiningStartsOnField, value) != true)) {
                    this.DiningStartsOnField = value;
                    this.RaisePropertyChanged("DiningStartsOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> DiningToTime {
            get {
                return this.DiningToTimeField;
            }
            set {
                if ((this.DiningToTimeField.Equals(value) != true)) {
                    this.DiningToTimeField = value;
                    this.RaisePropertyChanged("DiningToTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeoLocationName {
            get {
                return this.GeoLocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GeoLocationNameField, value) != true)) {
                    this.GeoLocationNameField = value;
                    this.RaisePropertyChanged("GeoLocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HighlightNames {
            get {
                return this.HighlightNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.HighlightNamesField, value) != true)) {
                    this.HighlightNamesField = value;
                    this.RaisePropertyChanged("HighlightNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewAmenities {
            get {
                return this.NewAmenitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.NewAmenitiesField, value) != true)) {
                    this.NewAmenitiesField = value;
                    this.RaisePropertyChanged("NewAmenities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileImageName {
            get {
                return this.ProfileImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageNameField, value) != true)) {
                    this.ProfileImageNameField = value;
                    this.RaisePropertyChanged("ProfileImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileImageNewName {
            get {
                return this.ProfileImageNewNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageNewNameField, value) != true)) {
                    this.ProfileImageNewNameField = value;
                    this.RaisePropertyChanged("ProfileImageNewName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ratings {
            get {
                return this.RatingsField;
            }
            set {
                if ((this.RatingsField.Equals(value) != true)) {
                    this.RatingsField = value;
                    this.RaisePropertyChanged("Ratings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referral {
            get {
                return this.ReferralField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferralField, value) != true)) {
                    this.ReferralField = value;
                    this.RaisePropertyChanged("Referral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RestChairProfileId {
            get {
                return this.RestChairProfileIdField;
            }
            set {
                if ((this.RestChairProfileIdField.Equals(value) != true)) {
                    this.RestChairProfileIdField = value;
                    this.RaisePropertyChanged("RestChairProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateId {
            get {
                return this.StateIdField;
            }
            set {
                if ((this.StateIdField.Equals(value) != true)) {
                    this.StateIdField = value;
                    this.RaisePropertyChanged("StateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string highlights {
            get {
                return this.highlightsField;
            }
            set {
                if ((object.ReferenceEquals(this.highlightsField, value) != true)) {
                    this.highlightsField = value;
                    this.RaisePropertyChanged("highlights");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ATRCCenter", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class ATRCCenter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ATRCIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATRCNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATRCNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATRCTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ATRCTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmenitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmenitiesNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmtForFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AvailableChairField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BasicPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BookedChairField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuisinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiningFacilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> DiningFromTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> DiningToTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeoLocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileImageNewNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RatingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string highlightsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ATRCId {
            get {
                return this.ATRCIdField;
            }
            set {
                if ((this.ATRCIdField.Equals(value) != true)) {
                    this.ATRCIdField = value;
                    this.RaisePropertyChanged("ATRCId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATRCName {
            get {
                return this.ATRCNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ATRCNameField, value) != true)) {
                    this.ATRCNameField = value;
                    this.RaisePropertyChanged("ATRCName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATRCNumber {
            get {
                return this.ATRCNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ATRCNumberField, value) != true)) {
                    this.ATRCNumberField = value;
                    this.RaisePropertyChanged("ATRCNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATRCType {
            get {
                return this.ATRCTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ATRCTypeField, value) != true)) {
                    this.ATRCTypeField = value;
                    this.RaisePropertyChanged("ATRCType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ATRCTypeId {
            get {
                return this.ATRCTypeIdField;
            }
            set {
                if ((this.ATRCTypeIdField.Equals(value) != true)) {
                    this.ATRCTypeIdField = value;
                    this.RaisePropertyChanged("ATRCTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amenities {
            get {
                return this.AmenitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.AmenitiesField, value) != true)) {
                    this.AmenitiesField = value;
                    this.RaisePropertyChanged("Amenities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmenitiesNames {
            get {
                return this.AmenitiesNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.AmenitiesNamesField, value) != true)) {
                    this.AmenitiesNamesField = value;
                    this.RaisePropertyChanged("AmenitiesNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmtForFilter {
            get {
                return this.AmtForFilterField;
            }
            set {
                if ((object.ReferenceEquals(this.AmtForFilterField, value) != true)) {
                    this.AmtForFilterField = value;
                    this.RaisePropertyChanged("AmtForFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AvailableChair {
            get {
                return this.AvailableChairField;
            }
            set {
                if ((this.AvailableChairField.Equals(value) != true)) {
                    this.AvailableChairField = value;
                    this.RaisePropertyChanged("AvailableChair");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BasicPrice {
            get {
                return this.BasicPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.BasicPriceField, value) != true)) {
                    this.BasicPriceField = value;
                    this.RaisePropertyChanged("BasicPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BookedChair {
            get {
                return this.BookedChairField;
            }
            set {
                if ((this.BookedChairField.Equals(value) != true)) {
                    this.BookedChairField = value;
                    this.RaisePropertyChanged("BookedChair");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryNames {
            get {
                return this.CategoryNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNamesField, value) != true)) {
                    this.CategoryNamesField = value;
                    this.RaisePropertyChanged("CategoryNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuisines {
            get {
                return this.CuisinesField;
            }
            set {
                if ((object.ReferenceEquals(this.CuisinesField, value) != true)) {
                    this.CuisinesField = value;
                    this.RaisePropertyChanged("Cuisines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiningFacility {
            get {
                return this.DiningFacilityField;
            }
            set {
                if ((this.DiningFacilityField.Equals(value) != true)) {
                    this.DiningFacilityField = value;
                    this.RaisePropertyChanged("DiningFacility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> DiningFromTime {
            get {
                return this.DiningFromTimeField;
            }
            set {
                if ((this.DiningFromTimeField.Equals(value) != true)) {
                    this.DiningFromTimeField = value;
                    this.RaisePropertyChanged("DiningFromTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> DiningToTime {
            get {
                return this.DiningToTimeField;
            }
            set {
                if ((this.DiningToTimeField.Equals(value) != true)) {
                    this.DiningToTimeField = value;
                    this.RaisePropertyChanged("DiningToTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeoLocationName {
            get {
                return this.GeoLocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GeoLocationNameField, value) != true)) {
                    this.GeoLocationNameField = value;
                    this.RaisePropertyChanged("GeoLocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileImageName {
            get {
                return this.ProfileImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageNameField, value) != true)) {
                    this.ProfileImageNameField = value;
                    this.RaisePropertyChanged("ProfileImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileImageNewName {
            get {
                return this.ProfileImageNewNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageNewNameField, value) != true)) {
                    this.ProfileImageNewNameField = value;
                    this.RaisePropertyChanged("ProfileImageNewName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ratings {
            get {
                return this.RatingsField;
            }
            set {
                if ((this.RatingsField.Equals(value) != true)) {
                    this.RatingsField = value;
                    this.RaisePropertyChanged("Ratings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referral {
            get {
                return this.ReferralField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferralField, value) != true)) {
                    this.ReferralField = value;
                    this.RaisePropertyChanged("Referral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateId {
            get {
                return this.StateIdField;
            }
            set {
                if ((this.StateIdField.Equals(value) != true)) {
                    this.StateIdField = value;
                    this.RaisePropertyChanged("StateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string highlights {
            get {
                return this.highlightsField;
            }
            set {
                if ((object.ReferenceEquals(this.highlightsField, value) != true)) {
                    this.highlightsField = value;
                    this.RaisePropertyChanged("highlights");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRestChairByAtrcId", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class GetRestChairByAtrcId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ATRCIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATRCNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATRCPolicyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ATRCRestChairIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmenitiesNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CancellationPolicyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChairCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan CheckInTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan CheckOutTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestchairField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ATRCId {
            get {
                return this.ATRCIdField;
            }
            set {
                if ((this.ATRCIdField.Equals(value) != true)) {
                    this.ATRCIdField = value;
                    this.RaisePropertyChanged("ATRCId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATRCName {
            get {
                return this.ATRCNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ATRCNameField, value) != true)) {
                    this.ATRCNameField = value;
                    this.RaisePropertyChanged("ATRCName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATRCPolicy {
            get {
                return this.ATRCPolicyField;
            }
            set {
                if ((object.ReferenceEquals(this.ATRCPolicyField, value) != true)) {
                    this.ATRCPolicyField = value;
                    this.RaisePropertyChanged("ATRCPolicy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ATRCRestChairId {
            get {
                return this.ATRCRestChairIdField;
            }
            set {
                if ((this.ATRCRestChairIdField.Equals(value) != true)) {
                    this.ATRCRestChairIdField = value;
                    this.RaisePropertyChanged("ATRCRestChairId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmenitiesNames {
            get {
                return this.AmenitiesNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.AmenitiesNamesField, value) != true)) {
                    this.AmenitiesNamesField = value;
                    this.RaisePropertyChanged("AmenitiesNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CancellationPolicy {
            get {
                return this.CancellationPolicyField;
            }
            set {
                if ((object.ReferenceEquals(this.CancellationPolicyField, value) != true)) {
                    this.CancellationPolicyField = value;
                    this.RaisePropertyChanged("CancellationPolicy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChairCount {
            get {
                return this.ChairCountField;
            }
            set {
                if ((this.ChairCountField.Equals(value) != true)) {
                    this.ChairCountField = value;
                    this.RaisePropertyChanged("ChairCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan CheckInTime {
            get {
                return this.CheckInTimeField;
            }
            set {
                if ((this.CheckInTimeField.Equals(value) != true)) {
                    this.CheckInTimeField = value;
                    this.RaisePropertyChanged("CheckInTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan CheckOutTime {
            get {
                return this.CheckOutTimeField;
            }
            set {
                if ((this.CheckOutTimeField.Equals(value) != true)) {
                    this.CheckOutTimeField = value;
                    this.RaisePropertyChanged("CheckOutTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Restchair {
            get {
                return this.RestchairField;
            }
            set {
                if ((object.ReferenceEquals(this.RestchairField, value) != true)) {
                    this.RestchairField = value;
                    this.RaisePropertyChanged("Restchair");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRestChairbyId", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class GetRestChairbyId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ATRCRestChairIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChairIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChairNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ATRCRestChairId {
            get {
                return this.ATRCRestChairIdField;
            }
            set {
                if ((this.ATRCRestChairIdField.Equals(value) != true)) {
                    this.ATRCRestChairIdField = value;
                    this.RaisePropertyChanged("ATRCRestChairId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChairId {
            get {
                return this.ChairIdField;
            }
            set {
                if ((this.ChairIdField.Equals(value) != true)) {
                    this.ChairIdField = value;
                    this.RaisePropertyChanged("ChairId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChairNumber {
            get {
                return this.ChairNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ChairNumberField, value) != true)) {
                    this.ChairNumberField = value;
                    this.RaisePropertyChanged("ChairNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ATRCServiceReference.IATRCService")]
    public interface IATRCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/InsertATRC", ReplyAction="http://tempuri.org/IATRCService/InsertATRCResponse")]
        int InsertATRC(JustStay.Services.DTO.ATRCDto center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/InsertATRC", ReplyAction="http://tempuri.org/IATRCService/InsertATRCResponse")]
        System.Threading.Tasks.Task<int> InsertATRCAsync(JustStay.Services.DTO.ATRCDto center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCIdByProfileID", ReplyAction="http://tempuri.org/IATRCService/GetATRCIdByProfileIDResponse")]
        int GetATRCIdByProfileID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCIdByProfileID", ReplyAction="http://tempuri.org/IATRCService/GetATRCIdByProfileIDResponse")]
        System.Threading.Tasks.Task<int> GetATRCIdByProfileIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCById", ReplyAction="http://tempuri.org/IATRCService/GetATRCByIdResponse")]
        JustStay.Services.DTO.ATRCDto GetATRCById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCById", ReplyAction="http://tempuri.org/IATRCService/GetATRCByIdResponse")]
        System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCDto> GetATRCByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCByUserId", ReplyAction="http://tempuri.org/IATRCService/GetATRCByUserIdResponse")]
        JustStay.Services.DTO.ATRCDto GetATRCByUserId(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCByUserId", ReplyAction="http://tempuri.org/IATRCService/GetATRCByUserIdResponse")]
        System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCDto> GetATRCByUserIdAsync(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCByIds", ReplyAction="http://tempuri.org/IATRCService/GetATRCByIdsResponse")]
        JustStay.Services.DTO.ATRCDto[] GetATRCByIds(int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCByIds", ReplyAction="http://tempuri.org/IATRCService/GetATRCByIdsResponse")]
        System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCDto[]> GetATRCByIdsAsync(int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/getAllATRC", ReplyAction="http://tempuri.org/IATRCService/getAllATRCResponse")]
        JustStay.Services.DTO.ATRCDto[] getAllATRC(int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/getAllATRC", ReplyAction="http://tempuri.org/IATRCService/getAllATRCResponse")]
        System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCDto[]> getAllATRCAsync(int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCProfileById", ReplyAction="http://tempuri.org/IATRCService/GetATRCProfileByIdResponse")]
        JustStay.Web.ATRCServiceReference.ATRCProfile GetATRCProfileById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCProfileById", ReplyAction="http://tempuri.org/IATRCService/GetATRCProfileByIdResponse")]
        System.Threading.Tasks.Task<JustStay.Web.ATRCServiceReference.ATRCProfile> GetATRCProfileByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/SearchATRCCenters", ReplyAction="http://tempuri.org/IATRCService/SearchATRCCentersResponse")]
        JustStay.Web.ATRCServiceReference.ATRCCenter[] SearchATRCCenters(decimal minLat, decimal maxLtd, decimal minLng, decimal maxLng, string mode, string search, System.Nullable<System.DateTime> date, int hour, int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/SearchATRCCenters", ReplyAction="http://tempuri.org/IATRCService/SearchATRCCentersResponse")]
        System.Threading.Tasks.Task<JustStay.Web.ATRCServiceReference.ATRCCenter[]> SearchATRCCentersAsync(decimal minLat, decimal maxLtd, decimal minLng, decimal maxLng, string mode, string search, System.Nullable<System.DateTime> date, int hour, int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/UpdateATRCStatus", ReplyAction="http://tempuri.org/IATRCService/UpdateATRCStatusResponse")]
        void UpdateATRCStatus(int artcid, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/UpdateATRCStatus", ReplyAction="http://tempuri.org/IATRCService/UpdateATRCStatusResponse")]
        System.Threading.Tasks.Task UpdateATRCStatusAsync(int artcid, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/UpdateATRC", ReplyAction="http://tempuri.org/IATRCService/UpdateATRCResponse")]
        void UpdateATRC(JustStay.Services.DTO.ATRCDto center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/UpdateATRC", ReplyAction="http://tempuri.org/IATRCService/UpdateATRCResponse")]
        System.Threading.Tasks.Task UpdateATRCAsync(JustStay.Services.DTO.ATRCDto center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/UpdateProfileImage", ReplyAction="http://tempuri.org/IATRCService/UpdateProfileImageResponse")]
        void UpdateProfileImage(JustStay.Services.DTO.ATRCDto center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/UpdateProfileImage", ReplyAction="http://tempuri.org/IATRCService/UpdateProfileImageResponse")]
        System.Threading.Tasks.Task UpdateProfileImageAsync(JustStay.Services.DTO.ATRCDto center);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetAllATRCImagesById", ReplyAction="http://tempuri.org/IATRCService/GetAllATRCImagesByIdResponse")]
        JustStay.Services.DTO.ATRCImageDto[] GetAllATRCImagesById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetAllATRCImagesById", ReplyAction="http://tempuri.org/IATRCService/GetAllATRCImagesByIdResponse")]
        System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCImageDto[]> GetAllATRCImagesByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/InsertATRCImage", ReplyAction="http://tempuri.org/IATRCService/InsertATRCImageResponse")]
        void InsertATRCImage(JustStay.Services.DTO.ATRCImageDto image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/InsertATRCImage", ReplyAction="http://tempuri.org/IATRCService/InsertATRCImageResponse")]
        System.Threading.Tasks.Task InsertATRCImageAsync(JustStay.Services.DTO.ATRCImageDto image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/DeleteATRCImage", ReplyAction="http://tempuri.org/IATRCService/DeleteATRCImageResponse")]
        void DeleteATRCImage(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/DeleteATRCImage", ReplyAction="http://tempuri.org/IATRCService/DeleteATRCImageResponse")]
        System.Threading.Tasks.Task DeleteATRCImageAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/UpdateATRCImageSD", ReplyAction="http://tempuri.org/IATRCService/UpdateATRCImageSDResponse")]
        void UpdateATRCImageSD(JustStay.Services.DTO.ATRCImageDto atrcimage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/UpdateATRCImageSD", ReplyAction="http://tempuri.org/IATRCService/UpdateATRCImageSDResponse")]
        System.Threading.Tasks.Task UpdateATRCImageSDAsync(JustStay.Services.DTO.ATRCImageDto atrcimage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/UpdateATRCProfile", ReplyAction="http://tempuri.org/IATRCService/UpdateATRCProfileResponse")]
        void UpdateATRCProfile(JustStay.Services.DTO.ATRCImageDto atrcimage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/UpdateATRCProfile", ReplyAction="http://tempuri.org/IATRCService/UpdateATRCProfileResponse")]
        System.Threading.Tasks.Task UpdateATRCProfileAsync(JustStay.Services.DTO.ATRCImageDto atrcimage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCSDImages", ReplyAction="http://tempuri.org/IATRCService/GetATRCSDImagesResponse")]
        JustStay.Services.DTO.ATRCImageDto[] GetATRCSDImages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetATRCSDImages", ReplyAction="http://tempuri.org/IATRCService/GetATRCSDImagesResponse")]
        System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCImageDto[]> GetATRCSDImagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetRestChairDetailsByAtrcId", ReplyAction="http://tempuri.org/IATRCService/GetRestChairDetailsByAtrcIdResponse")]
        JustStay.Web.ATRCServiceReference.GetRestChairByAtrcId[] GetRestChairDetailsByAtrcId(int atrcid, System.DateTime date, int hour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetRestChairDetailsByAtrcId", ReplyAction="http://tempuri.org/IATRCService/GetRestChairDetailsByAtrcIdResponse")]
        System.Threading.Tasks.Task<JustStay.Web.ATRCServiceReference.GetRestChairByAtrcId[]> GetRestChairDetailsByAtrcIdAsync(int atrcid, System.DateTime date, int hour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetRestchair", ReplyAction="http://tempuri.org/IATRCService/GetRestchairResponse")]
        JustStay.Web.ATRCServiceReference.GetRestChairbyId[] GetRestchair(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATRCService/GetRestchair", ReplyAction="http://tempuri.org/IATRCService/GetRestchairResponse")]
        System.Threading.Tasks.Task<JustStay.Web.ATRCServiceReference.GetRestChairbyId[]> GetRestchairAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IATRCServiceChannel : JustStay.Web.ATRCServiceReference.IATRCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATRCServiceClient : System.ServiceModel.ClientBase<JustStay.Web.ATRCServiceReference.IATRCService>, JustStay.Web.ATRCServiceReference.IATRCService {
        
        public ATRCServiceClient() {
        }
        
        public ATRCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATRCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATRCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATRCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertATRC(JustStay.Services.DTO.ATRCDto center) {
            return base.Channel.InsertATRC(center);
        }
        
        public System.Threading.Tasks.Task<int> InsertATRCAsync(JustStay.Services.DTO.ATRCDto center) {
            return base.Channel.InsertATRCAsync(center);
        }
        
        public int GetATRCIdByProfileID(int id) {
            return base.Channel.GetATRCIdByProfileID(id);
        }
        
        public System.Threading.Tasks.Task<int> GetATRCIdByProfileIDAsync(int id) {
            return base.Channel.GetATRCIdByProfileIDAsync(id);
        }
        
        public JustStay.Services.DTO.ATRCDto GetATRCById(int id) {
            return base.Channel.GetATRCById(id);
        }
        
        public System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCDto> GetATRCByIdAsync(int id) {
            return base.Channel.GetATRCByIdAsync(id);
        }
        
        public JustStay.Services.DTO.ATRCDto GetATRCByUserId(int userid) {
            return base.Channel.GetATRCByUserId(userid);
        }
        
        public System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCDto> GetATRCByUserIdAsync(int userid) {
            return base.Channel.GetATRCByUserIdAsync(userid);
        }
        
        public JustStay.Services.DTO.ATRCDto[] GetATRCByIds(int[] ids) {
            return base.Channel.GetATRCByIds(ids);
        }
        
        public System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCDto[]> GetATRCByIdsAsync(int[] ids) {
            return base.Channel.GetATRCByIdsAsync(ids);
        }
        
        public JustStay.Services.DTO.ATRCDto[] getAllATRC(int status) {
            return base.Channel.getAllATRC(status);
        }
        
        public System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCDto[]> getAllATRCAsync(int status) {
            return base.Channel.getAllATRCAsync(status);
        }
        
        public JustStay.Web.ATRCServiceReference.ATRCProfile GetATRCProfileById(int id) {
            return base.Channel.GetATRCProfileById(id);
        }
        
        public System.Threading.Tasks.Task<JustStay.Web.ATRCServiceReference.ATRCProfile> GetATRCProfileByIdAsync(int id) {
            return base.Channel.GetATRCProfileByIdAsync(id);
        }
        
        public JustStay.Web.ATRCServiceReference.ATRCCenter[] SearchATRCCenters(decimal minLat, decimal maxLtd, decimal minLng, decimal maxLng, string mode, string search, System.Nullable<System.DateTime> date, int hour, int cityId) {
            return base.Channel.SearchATRCCenters(minLat, maxLtd, minLng, maxLng, mode, search, date, hour, cityId);
        }
        
        public System.Threading.Tasks.Task<JustStay.Web.ATRCServiceReference.ATRCCenter[]> SearchATRCCentersAsync(decimal minLat, decimal maxLtd, decimal minLng, decimal maxLng, string mode, string search, System.Nullable<System.DateTime> date, int hour, int cityId) {
            return base.Channel.SearchATRCCentersAsync(minLat, maxLtd, minLng, maxLng, mode, search, date, hour, cityId);
        }
        
        public void UpdateATRCStatus(int artcid, int status) {
            base.Channel.UpdateATRCStatus(artcid, status);
        }
        
        public System.Threading.Tasks.Task UpdateATRCStatusAsync(int artcid, int status) {
            return base.Channel.UpdateATRCStatusAsync(artcid, status);
        }
        
        public void UpdateATRC(JustStay.Services.DTO.ATRCDto center) {
            base.Channel.UpdateATRC(center);
        }
        
        public System.Threading.Tasks.Task UpdateATRCAsync(JustStay.Services.DTO.ATRCDto center) {
            return base.Channel.UpdateATRCAsync(center);
        }
        
        public void UpdateProfileImage(JustStay.Services.DTO.ATRCDto center) {
            base.Channel.UpdateProfileImage(center);
        }
        
        public System.Threading.Tasks.Task UpdateProfileImageAsync(JustStay.Services.DTO.ATRCDto center) {
            return base.Channel.UpdateProfileImageAsync(center);
        }
        
        public JustStay.Services.DTO.ATRCImageDto[] GetAllATRCImagesById(int id) {
            return base.Channel.GetAllATRCImagesById(id);
        }
        
        public System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCImageDto[]> GetAllATRCImagesByIdAsync(int id) {
            return base.Channel.GetAllATRCImagesByIdAsync(id);
        }
        
        public void InsertATRCImage(JustStay.Services.DTO.ATRCImageDto image) {
            base.Channel.InsertATRCImage(image);
        }
        
        public System.Threading.Tasks.Task InsertATRCImageAsync(JustStay.Services.DTO.ATRCImageDto image) {
            return base.Channel.InsertATRCImageAsync(image);
        }
        
        public void DeleteATRCImage(int id) {
            base.Channel.DeleteATRCImage(id);
        }
        
        public System.Threading.Tasks.Task DeleteATRCImageAsync(int id) {
            return base.Channel.DeleteATRCImageAsync(id);
        }
        
        public void UpdateATRCImageSD(JustStay.Services.DTO.ATRCImageDto atrcimage) {
            base.Channel.UpdateATRCImageSD(atrcimage);
        }
        
        public System.Threading.Tasks.Task UpdateATRCImageSDAsync(JustStay.Services.DTO.ATRCImageDto atrcimage) {
            return base.Channel.UpdateATRCImageSDAsync(atrcimage);
        }
        
        public void UpdateATRCProfile(JustStay.Services.DTO.ATRCImageDto atrcimage) {
            base.Channel.UpdateATRCProfile(atrcimage);
        }
        
        public System.Threading.Tasks.Task UpdateATRCProfileAsync(JustStay.Services.DTO.ATRCImageDto atrcimage) {
            return base.Channel.UpdateATRCProfileAsync(atrcimage);
        }
        
        public JustStay.Services.DTO.ATRCImageDto[] GetATRCSDImages() {
            return base.Channel.GetATRCSDImages();
        }
        
        public System.Threading.Tasks.Task<JustStay.Services.DTO.ATRCImageDto[]> GetATRCSDImagesAsync() {
            return base.Channel.GetATRCSDImagesAsync();
        }
        
        public JustStay.Web.ATRCServiceReference.GetRestChairByAtrcId[] GetRestChairDetailsByAtrcId(int atrcid, System.DateTime date, int hour) {
            return base.Channel.GetRestChairDetailsByAtrcId(atrcid, date, hour);
        }
        
        public System.Threading.Tasks.Task<JustStay.Web.ATRCServiceReference.GetRestChairByAtrcId[]> GetRestChairDetailsByAtrcIdAsync(int atrcid, System.DateTime date, int hour) {
            return base.Channel.GetRestChairDetailsByAtrcIdAsync(atrcid, date, hour);
        }
        
        public JustStay.Web.ATRCServiceReference.GetRestChairbyId[] GetRestchair(int id) {
            return base.Channel.GetRestchair(id);
        }
        
        public System.Threading.Tasks.Task<JustStay.Web.ATRCServiceReference.GetRestChairbyId[]> GetRestchairAsync(int id) {
            return base.Channel.GetRestchairAsync(id);
        }
    }
}
