
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    using System.Collections.Generic;
    
public partial class ATRCAmenity
{

    public int AmenityId { get; set; }

    public int ATRCId { get; set; }

    public bool Parking { get; set; }

    public bool Wifi { get; set; }

    public bool Restaurant { get; set; }

    public bool CleanBathRoom { get; set; }

}

}
