
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class ATRCOnlineBillingFromJuststay
{

    public string Perticulars { get; set; }

    public string PaymentMode { get; set; }

    public Nullable<decimal> NetAmount { get; set; }

    public int GST { get; set; }

    public Nullable<decimal> ATRCCommission { get; set; }

}

}
