
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class ATRCProfile
{

    public int ATRCId { get; set; }

    public string ATRCName { get; set; }

    public string Category { get; set; }

    public string OwnerName { get; set; }

    public string Address { get; set; }

    public int StateId { get; set; }

    public int CityId { get; set; }

    public string Telephone { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public string Referral { get; set; }

    public Nullable<int> LocationId { get; set; }

    public Nullable<int> UserId { get; set; }

    public Nullable<int> Status { get; set; }

    public string ATRCNumber { get; set; }

    public string StateName { get; set; }

    public string CityName { get; set; }

    public string LocationName { get; set; }

    public string Details { get; set; }

    public Nullable<int> DiningFacility { get; set; }

    public Nullable<System.TimeSpan> DiningFromTime { get; set; }

    public Nullable<System.TimeSpan> DiningToTime { get; set; }

    public string DiningFacilityName { get; set; }

    public string DiningStartsOn { get; set; }

    public string DiningEndsOn { get; set; }

    public string CategoryNames { get; set; }

    public string ProfileImageName { get; set; }

    public string ProfileImageNewName { get; set; }

    public Nullable<decimal> Latitude { get; set; }

    public Nullable<decimal> Longitude { get; set; }

    public string highlights { get; set; }

    public string Cuisines { get; set; }

    public string Amenities { get; set; }

    public string HighlightNames { get; set; }

    public string CuisinesNames { get; set; }

    public string AmenitiesNames { get; set; }

    public string GeoLocationName { get; set; }

    public int RestChairProfileId { get; set; }

    public Nullable<int> ATRCTypeId { get; set; }

    public string NewAmenities { get; set; }

    public Nullable<decimal> Ratings { get; set; }

}

}
