
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    using System.Collections.Generic;
    
public partial class ATRCRestChair
{

    public int ATRCRestChairId { get; set; }

    public string ChairName { get; set; }

    public int TypeId { get; set; }

    public int ChairCount { get; set; }

    public string Description { get; set; }

    public string Amenities { get; set; }

    public int RestChairProfileId { get; set; }

    public decimal Price { get; set; }

}

}
