
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    using System.Collections.Generic;
    
public partial class Blog
{

    public int BlogId { get; set; }

    public int BlogCategoryId { get; set; }

    public string BlogTitle { get; set; }

    public string BlogContent { get; set; }

    public System.DateTime BlogDate { get; set; }

    public string BlogImageName { get; set; }

    public string BlogImageNewName { get; set; }

    public System.DateTime InsertedOn { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

}

}
