
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class EmailInfo
{

    public string Name { get; set; }

    public string Email { get; set; }

    public int UserId { get; set; }

    public string UserType { get; set; }

}

}
