
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class GetAllPaymentByCustomerId
{

    public int ATRCId { get; set; }

    public string Address { get; set; }

    public string Mobile { get; set; }

    public string ATRCName { get; set; }

    public string BookingDate { get; set; }

    public string BookingNumber { get; set; }

    public Nullable<System.TimeSpan> FromTime { get; set; }

    public Nullable<System.TimeSpan> ToTime { get; set; }

    public decimal TotalAmount { get; set; }

    public string IsSuccess { get; set; }

    public string PaymentMode { get; set; }

    public int RestChairBookingId { get; set; }

    public int CustomerId { get; set; }

    public int UserId { get; set; }

}

}
