
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class GetAllCustomersDetails
{

    public int CustomerId { get; set; }

    public string Name { get; set; }

    public int UserId { get; set; }

    public string Mobile { get; set; }

    public string CustType { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string Gender { get; set; }

    public Nullable<int> BookingCount { get; set; }

}

}
