
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class GetAllBookingByCustomerIdAndroid
{

    public Nullable<int> UserId { get; set; }

    public int CustomerId { get; set; }

    public int ATRCId { get; set; }

    public int RestChairBookingId { get; set; }

    public string BookingDate { get; set; }

    public string BookingNumber { get; set; }

    public string FromTime { get; set; }

    public string ToTime { get; set; }

    public string Hour { get; set; }

    public string Person { get; set; }

    public string ATRCName { get; set; }

    public string ATRCNumber { get; set; }

    public string Chairs { get; set; }

    public string CustomerName { get; set; }

    public string CustomerMobile { get; set; }

    public string NetAmount { get; set; }

    public string Status { get; set; }

    public string PaymentMode { get; set; }

    public string orderid { get; set; }

    public string OTP { get; set; }

    public Nullable<bool> IsSuccess { get; set; }

}

}
