
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class GetCustomerBookingsByATRC
{

    public int CustomerId { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string Name { get; set; }

    public string Mobile { get; set; }

    public string CustType { get; set; }

    public Nullable<System.DateTime> BookingDate { get; set; }

    public Nullable<System.TimeSpan> FromTime { get; set; }

    public Nullable<System.TimeSpan> ToTime { get; set; }

    public Nullable<int> Person { get; set; }

    public Nullable<int> Hour { get; set; }

    public string BookingNumber { get; set; }

    public string BookingStatus { get; set; }

    public Nullable<decimal> NetAmount { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public string PaymentMode { get; set; }

    public Nullable<decimal> CGST { get; set; }

    public Nullable<decimal> SGST { get; set; }

    public Nullable<int> Discount { get; set; }

    public Nullable<bool> IsSuccess { get; set; }

    public string MerchantTxnId { get; set; }

    public string OTP { get; set; }

    public Nullable<decimal> TotalAmount { get; set; }

}

}
