
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class GetRestChairbyId
{

    public int ChairId { get; set; }

    public int ATRCRestChairId { get; set; }

    public string ChairNumber { get; set; }

}

}
