
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class GetRestChairBookingByATRC
{

    public int ATRCId { get; set; }

    public int RestChairBookingId { get; set; }

    public string BookingDetails { get; set; }

    public string Chairs { get; set; }

    public string CustDetails { get; set; }

    public string PayStatus { get; set; }

    public int RCPaymentId { get; set; }

    public System.DateTime Paydate { get; set; }

    public string ATRCPaystatus { get; set; }

    public string PaymentMode { get; set; }

}

}
