
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class GetTodaysBooking
{

    public int ATRCId { get; set; }

    public int RestChairBookingId { get; set; }

    public string BookingNumber { get; set; }

    public string ATRCName { get; set; }

    public Nullable<System.DateTime> BookingDate { get; set; }

    public string PaymentMode { get; set; }

    public string CustDetails { get; set; }

}

}
