
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class InboxMail
{

    public int MessageId { get; set; }

    public string Subject { get; set; }

    public string FromEmail { get; set; }

    public System.DateTime InsertedOn { get; set; }

    public bool UnRead { get; set; }

}

}
