
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    using System.Collections.Generic;
    
public partial class Message
{

    public int MessageId { get; set; }

    public string Subject { get; set; }

    public string EmailBody { get; set; }

    public Nullable<int> RefrenceId { get; set; }

    public System.DateTime InsertedOn { get; set; }

    public int InsertedBy { get; set; }

    public int MessageSource { get; set; }

}

}
