
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    using System.Collections.Generic;
    
public partial class Offer
{

    public int OfferId { get; set; }

    public string Heading { get; set; }

    public string SubHeading { get; set; }

    public string ShortDetail { get; set; }

    public string Details { get; set; }

    public string OfferImage { get; set; }

    public string OfferImgNewName { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<System.DateTime> InsertedOn { get; set; }

}

}
