
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    using System.Collections.Generic;
    
public partial class RCPayment
{

    public int RCPaymentId { get; set; }

    public Nullable<int> RestChairBookingId { get; set; }

    public Nullable<decimal> TotalAmount { get; set; }

    public Nullable<int> Discount { get; set; }

    public Nullable<decimal> NetAmount { get; set; }

    public Nullable<decimal> CGST { get; set; }

    public Nullable<decimal> SGST { get; set; }

    public string MerchantTxnId { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public Nullable<bool> IsSuccess { get; set; }

    public Nullable<System.DateTime> InsertedOn { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public string PaymentMode { get; set; }

    public string OTP { get; set; }

    public string order_id { get; set; }

    public string razorpay_payment_id { get; set; }

    public string razorpay_signature { get; set; }

    public string Paystatus { get; set; }

    public Nullable<System.DateTime> Paydate { get; set; }

}

}
