
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    using System.Collections.Generic;
    
public partial class Setting
{

    public int SettingId { get; set; }

    public string SmsUrl { get; set; }

    public string SmsUsername { get; set; }

    public string SmsPassword { get; set; }

    public string SmsSenderId { get; set; }

    public string SMSBalanceUrl { get; set; }

    public string privacy { get; set; }

}

}
