
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    using System.Collections.Generic;
    
public partial class SMSTemplate
{

    public int TemplateId { get; set; }

    public string Name { get; set; }

    public string Template { get; set; }

    public Nullable<System.DateTime> InsertedOn { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
