
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JustStay.Repo
{

using System;
    
public partial class UserDetail
{

    public int UserId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public Nullable<int> UserTypeId { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<bool> IsPaid { get; set; }

    public Nullable<System.DateTime> InsertedOn { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> RoleId { get; set; }

    public Nullable<bool> IsAdmin { get; set; }

    public string UserType { get; set; }

    public string Role { get; set; }

    public string Google_Id { get; set; }

}

}
