//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustStay.ATRC.CommonServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class State : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameWithCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameWithCode {
            get {
                return this.NameWithCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NameWithCodeField, value) != true)) {
                    this.NameWithCodeField = value;
                    this.RaisePropertyChanged("NameWithCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateId {
            get {
                return this.StateIdField;
            }
            set {
                if ((this.StateIdField.Equals(value) != true)) {
                    this.StateIdField = value;
                    this.RaisePropertyChanged("StateId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InsertedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> longitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InsertedOn {
            get {
                return this.InsertedOnField;
            }
            set {
                if ((this.InsertedOnField.Equals(value) != true)) {
                    this.InsertedOnField = value;
                    this.RaisePropertyChanged("InsertedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((this.UpdatedOnField.Equals(value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InsertedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> longitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InsertedOn {
            get {
                return this.InsertedOnField;
            }
            set {
                if ((this.InsertedOnField.Equals(value) != true)) {
                    this.InsertedOnField = value;
                    this.RaisePropertyChanged("InsertedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((this.UpdatedOnField.Equals(value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ATRCCategory", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class ATRCCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ATRCCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InsertedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ATRCCategoryId {
            get {
                return this.ATRCCategoryIdField;
            }
            set {
                if ((this.ATRCCategoryIdField.Equals(value) != true)) {
                    this.ATRCCategoryIdField = value;
                    this.RaisePropertyChanged("ATRCCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InsertedOn {
            get {
                return this.InsertedOnField;
            }
            set {
                if ((this.InsertedOnField.Equals(value) != true)) {
                    this.InsertedOnField = value;
                    this.RaisePropertyChanged("InsertedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ATRCSubCategory", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class ATRCSubCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ATRCCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ATRCSubCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InsertedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ATRCCategoryId {
            get {
                return this.ATRCCategoryIdField;
            }
            set {
                if ((this.ATRCCategoryIdField.Equals(value) != true)) {
                    this.ATRCCategoryIdField = value;
                    this.RaisePropertyChanged("ATRCCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ATRCSubCategoryId {
            get {
                return this.ATRCSubCategoryIdField;
            }
            set {
                if ((this.ATRCSubCategoryIdField.Equals(value) != true)) {
                    this.ATRCSubCategoryIdField = value;
                    this.RaisePropertyChanged("ATRCSubCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InsertedOn {
            get {
                return this.InsertedOnField;
            }
            set {
                if ((this.InsertedOnField.Equals(value) != true)) {
                    this.InsertedOnField = value;
                    this.RaisePropertyChanged("InsertedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategory {
            get {
                return this.SubCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryField, value) != true)) {
                    this.SubCategoryField = value;
                    this.RaisePropertyChanged("SubCategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SettingDto", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class SettingDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSBalanceUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SettingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsSenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string privacyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMSBalanceUrl {
            get {
                return this.SMSBalanceUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSBalanceUrlField, value) != true)) {
                    this.SMSBalanceUrlField = value;
                    this.RaisePropertyChanged("SMSBalanceUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SettingId {
            get {
                return this.SettingIdField;
            }
            set {
                if ((this.SettingIdField.Equals(value) != true)) {
                    this.SettingIdField = value;
                    this.RaisePropertyChanged("SettingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsPassword {
            get {
                return this.SmsPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsPasswordField, value) != true)) {
                    this.SmsPasswordField = value;
                    this.RaisePropertyChanged("SmsPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsSenderId {
            get {
                return this.SmsSenderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsSenderIdField, value) != true)) {
                    this.SmsSenderIdField = value;
                    this.RaisePropertyChanged("SmsSenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsUrl {
            get {
                return this.SmsUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsUrlField, value) != true)) {
                    this.SmsUrlField = value;
                    this.RaisePropertyChanged("SmsUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsUsername {
            get {
                return this.SmsUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsUsernameField, value) != true)) {
                    this.SmsUsernameField = value;
                    this.RaisePropertyChanged("SmsUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string privacy {
            get {
                return this.privacyField;
            }
            set {
                if ((object.ReferenceEquals(this.privacyField, value) != true)) {
                    this.privacyField = value;
                    this.RaisePropertyChanged("privacy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSTemplateDto", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class SMSTemplateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InsertedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InsertedOn {
            get {
                return this.InsertedOnField;
            }
            set {
                if ((this.InsertedOnField.Equals(value) != true)) {
                    this.InsertedOnField = value;
                    this.RaisePropertyChanged("InsertedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Template {
            get {
                return this.TemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateField, value) != true)) {
                    this.TemplateField = value;
                    this.RaisePropertyChanged("Template");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateId {
            get {
                return this.TemplateIdField;
            }
            set {
                if ((this.TemplateIdField.Equals(value) != true)) {
                    this.TemplateIdField = value;
                    this.RaisePropertyChanged("TemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((this.UpdatedOnField.Equals(value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Localities", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class Localities : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ATRCType", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Repo")]
    [System.SerializableAttribute()]
    public partial class ATRCType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ATRCTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InsertedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ATRCTypeId {
            get {
                return this.ATRCTypeIdField;
            }
            set {
                if ((this.ATRCTypeIdField.Equals(value) != true)) {
                    this.ATRCTypeIdField = value;
                    this.RaisePropertyChanged("ATRCTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertedOn {
            get {
                return this.InsertedOnField;
            }
            set {
                if ((this.InsertedOnField.Equals(value) != true)) {
                    this.InsertedOnField = value;
                    this.RaisePropertyChanged("InsertedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((this.UpdatedOnField.Equals(value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentDto", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class AttachmentDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttachmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNewNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MasterTableIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttachmentId {
            get {
                return this.AttachmentIdField;
            }
            set {
                if ((this.AttachmentIdField.Equals(value) != true)) {
                    this.AttachmentIdField = value;
                    this.RaisePropertyChanged("AttachmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocName {
            get {
                return this.DocNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNameField, value) != true)) {
                    this.DocNameField = value;
                    this.RaisePropertyChanged("DocName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocNewName {
            get {
                return this.DocNewNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNewNameField, value) != true)) {
                    this.DocNewNameField = value;
                    this.RaisePropertyChanged("DocNewName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MasterTableId {
            get {
                return this.MasterTableIdField;
            }
            set {
                if ((this.MasterTableIdField.Equals(value) != true)) {
                    this.MasterTableIdField = value;
                    this.RaisePropertyChanged("MasterTableId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatingDto", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class RatingDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ATRCIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InsertedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ATRCId {
            get {
                return this.ATRCIdField;
            }
            set {
                if ((this.ATRCIdField.Equals(value) != true)) {
                    this.ATRCIdField = value;
                    this.RaisePropertyChanged("ATRCId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertedOn {
            get {
                return this.InsertedOnField;
            }
            set {
                if ((this.InsertedOnField.Equals(value) != true)) {
                    this.InsertedOnField = value;
                    this.RaisePropertyChanged("InsertedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RatingId {
            get {
                return this.RatingIdField;
            }
            set {
                if ((this.RatingIdField.Equals(value) != true)) {
                    this.RatingIdField = value;
                    this.RaisePropertyChanged("RatingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Star {
            get {
                return this.StarField;
            }
            set {
                if ((this.StarField.Equals(value) != true)) {
                    this.StarField = value;
                    this.RaisePropertyChanged("Star");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommonServiceReference.ICommonService")]
    public interface ICommonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllStates", ReplyAction="http://tempuri.org/ICommonService/GetAllStatesResponse")]
        JustStay.ATRC.CommonServiceReference.State[] GetAllStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllStates", ReplyAction="http://tempuri.org/ICommonService/GetAllStatesResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.State[]> GetAllStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllCities", ReplyAction="http://tempuri.org/ICommonService/GetAllCitiesResponse")]
        JustStay.ATRC.CommonServiceReference.City[] GetAllCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllCities", ReplyAction="http://tempuri.org/ICommonService/GetAllCitiesResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.City[]> GetAllCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllCitiesBySearch", ReplyAction="http://tempuri.org/ICommonService/GetAllCitiesBySearchResponse")]
        JustStay.ATRC.CommonServiceReference.City[] GetAllCitiesBySearch(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllCitiesBySearch", ReplyAction="http://tempuri.org/ICommonService/GetAllCitiesBySearchResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.City[]> GetAllCitiesBySearchAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAlLocationsByCity", ReplyAction="http://tempuri.org/ICommonService/GetAlLocationsByCityResponse")]
        JustStay.ATRC.CommonServiceReference.Location[] GetAlLocationsByCity(int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAlLocationsByCity", ReplyAction="http://tempuri.org/ICommonService/GetAlLocationsByCityResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.Location[]> GetAlLocationsByCityAsync(int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllATRCCategory", ReplyAction="http://tempuri.org/ICommonService/GetAllATRCCategoryResponse")]
        JustStay.ATRC.CommonServiceReference.ATRCCategory[] GetAllATRCCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllATRCCategory", ReplyAction="http://tempuri.org/ICommonService/GetAllATRCCategoryResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.ATRCCategory[]> GetAllATRCCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllATRCSubCategory", ReplyAction="http://tempuri.org/ICommonService/GetAllATRCSubCategoryResponse")]
        JustStay.ATRC.CommonServiceReference.ATRCSubCategory[] GetAllATRCSubCategory(int categoryid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllATRCSubCategory", ReplyAction="http://tempuri.org/ICommonService/GetAllATRCSubCategoryResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.ATRCSubCategory[]> GetAllATRCSubCategoryAsync(int categoryid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetSettings", ReplyAction="http://tempuri.org/ICommonService/GetSettingsResponse")]
        JustStay.ATRC.CommonServiceReference.SettingDto GetSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetSettings", ReplyAction="http://tempuri.org/ICommonService/GetSettingsResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.SettingDto> GetSettingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetSMSTemplateByName", ReplyAction="http://tempuri.org/ICommonService/GetSMSTemplateByNameResponse")]
        JustStay.ATRC.CommonServiceReference.SMSTemplateDto GetSMSTemplateByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetSMSTemplateByName", ReplyAction="http://tempuri.org/ICommonService/GetSMSTemplateByNameResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.SMSTemplateDto> GetSMSTemplateByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAutoLocalities", ReplyAction="http://tempuri.org/ICommonService/GetAutoLocalitiesResponse")]
        JustStay.ATRC.CommonServiceReference.Localities[] GetAutoLocalities(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAutoLocalities", ReplyAction="http://tempuri.org/ICommonService/GetAutoLocalitiesResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.Localities[]> GetAutoLocalitiesAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetATRCTypes", ReplyAction="http://tempuri.org/ICommonService/GetATRCTypesResponse")]
        JustStay.ATRC.CommonServiceReference.ATRCType[] GetATRCTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetATRCTypes", ReplyAction="http://tempuri.org/ICommonService/GetATRCTypesResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.ATRCType[]> GetATRCTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAttachementsByMaster", ReplyAction="http://tempuri.org/ICommonService/GetAttachementsByMasterResponse")]
        JustStay.ATRC.CommonServiceReference.AttachmentDto[] GetAttachementsByMaster(int masterId, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAttachementsByMaster", ReplyAction="http://tempuri.org/ICommonService/GetAttachementsByMasterResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.AttachmentDto[]> GetAttachementsByMasterAsync(int masterId, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/InsertAttachment", ReplyAction="http://tempuri.org/ICommonService/InsertAttachmentResponse")]
        void InsertAttachment(JustStay.ATRC.CommonServiceReference.AttachmentDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/InsertAttachment", ReplyAction="http://tempuri.org/ICommonService/InsertAttachmentResponse")]
        System.Threading.Tasks.Task InsertAttachmentAsync(JustStay.ATRC.CommonServiceReference.AttachmentDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/DeleteAttachment", ReplyAction="http://tempuri.org/ICommonService/DeleteAttachmentResponse")]
        void DeleteAttachment(int attchmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/DeleteAttachment", ReplyAction="http://tempuri.org/ICommonService/DeleteAttachmentResponse")]
        System.Threading.Tasks.Task DeleteAttachmentAsync(int attchmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/InsertRating", ReplyAction="http://tempuri.org/ICommonService/InsertRatingResponse")]
        void InsertRating(JustStay.ATRC.CommonServiceReference.RatingDto rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/InsertRating", ReplyAction="http://tempuri.org/ICommonService/InsertRatingResponse")]
        System.Threading.Tasks.Task InsertRatingAsync(JustStay.ATRC.CommonServiceReference.RatingDto rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllRating", ReplyAction="http://tempuri.org/ICommonService/GetAllRatingResponse")]
        JustStay.ATRC.CommonServiceReference.RatingDto[] GetAllRating(int atrcid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetAllRating", ReplyAction="http://tempuri.org/ICommonService/GetAllRatingResponse")]
        System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.RatingDto[]> GetAllRatingAsync(int atrcid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Encrypt", ReplyAction="http://tempuri.org/ICommonService/EncryptResponse")]
        string Encrypt(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Encrypt", ReplyAction="http://tempuri.org/ICommonService/EncryptResponse")]
        System.Threading.Tasks.Task<string> EncryptAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Decrypt", ReplyAction="http://tempuri.org/ICommonService/DecryptResponse")]
        string Decrypt(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Decrypt", ReplyAction="http://tempuri.org/ICommonService/DecryptResponse")]
        System.Threading.Tasks.Task<string> DecryptAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonServiceChannel : JustStay.ATRC.CommonServiceReference.ICommonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonServiceClient : System.ServiceModel.ClientBase<JustStay.ATRC.CommonServiceReference.ICommonService>, JustStay.ATRC.CommonServiceReference.ICommonService {
        
        public CommonServiceClient() {
        }
        
        public CommonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JustStay.ATRC.CommonServiceReference.State[] GetAllStates() {
            return base.Channel.GetAllStates();
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.State[]> GetAllStatesAsync() {
            return base.Channel.GetAllStatesAsync();
        }
        
        public JustStay.ATRC.CommonServiceReference.City[] GetAllCities() {
            return base.Channel.GetAllCities();
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.City[]> GetAllCitiesAsync() {
            return base.Channel.GetAllCitiesAsync();
        }
        
        public JustStay.ATRC.CommonServiceReference.City[] GetAllCitiesBySearch(string search) {
            return base.Channel.GetAllCitiesBySearch(search);
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.City[]> GetAllCitiesBySearchAsync(string search) {
            return base.Channel.GetAllCitiesBySearchAsync(search);
        }
        
        public JustStay.ATRC.CommonServiceReference.Location[] GetAlLocationsByCity(int cityId) {
            return base.Channel.GetAlLocationsByCity(cityId);
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.Location[]> GetAlLocationsByCityAsync(int cityId) {
            return base.Channel.GetAlLocationsByCityAsync(cityId);
        }
        
        public JustStay.ATRC.CommonServiceReference.ATRCCategory[] GetAllATRCCategory() {
            return base.Channel.GetAllATRCCategory();
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.ATRCCategory[]> GetAllATRCCategoryAsync() {
            return base.Channel.GetAllATRCCategoryAsync();
        }
        
        public JustStay.ATRC.CommonServiceReference.ATRCSubCategory[] GetAllATRCSubCategory(int categoryid) {
            return base.Channel.GetAllATRCSubCategory(categoryid);
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.ATRCSubCategory[]> GetAllATRCSubCategoryAsync(int categoryid) {
            return base.Channel.GetAllATRCSubCategoryAsync(categoryid);
        }
        
        public JustStay.ATRC.CommonServiceReference.SettingDto GetSettings() {
            return base.Channel.GetSettings();
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.SettingDto> GetSettingsAsync() {
            return base.Channel.GetSettingsAsync();
        }
        
        public JustStay.ATRC.CommonServiceReference.SMSTemplateDto GetSMSTemplateByName(string name) {
            return base.Channel.GetSMSTemplateByName(name);
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.SMSTemplateDto> GetSMSTemplateByNameAsync(string name) {
            return base.Channel.GetSMSTemplateByNameAsync(name);
        }
        
        public JustStay.ATRC.CommonServiceReference.Localities[] GetAutoLocalities(string search) {
            return base.Channel.GetAutoLocalities(search);
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.Localities[]> GetAutoLocalitiesAsync(string search) {
            return base.Channel.GetAutoLocalitiesAsync(search);
        }
        
        public JustStay.ATRC.CommonServiceReference.ATRCType[] GetATRCTypes() {
            return base.Channel.GetATRCTypes();
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.ATRCType[]> GetATRCTypesAsync() {
            return base.Channel.GetATRCTypesAsync();
        }
        
        public JustStay.ATRC.CommonServiceReference.AttachmentDto[] GetAttachementsByMaster(int masterId, string tableName) {
            return base.Channel.GetAttachementsByMaster(masterId, tableName);
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.AttachmentDto[]> GetAttachementsByMasterAsync(int masterId, string tableName) {
            return base.Channel.GetAttachementsByMasterAsync(masterId, tableName);
        }
        
        public void InsertAttachment(JustStay.ATRC.CommonServiceReference.AttachmentDto dto) {
            base.Channel.InsertAttachment(dto);
        }
        
        public System.Threading.Tasks.Task InsertAttachmentAsync(JustStay.ATRC.CommonServiceReference.AttachmentDto dto) {
            return base.Channel.InsertAttachmentAsync(dto);
        }
        
        public void DeleteAttachment(int attchmentId) {
            base.Channel.DeleteAttachment(attchmentId);
        }
        
        public System.Threading.Tasks.Task DeleteAttachmentAsync(int attchmentId) {
            return base.Channel.DeleteAttachmentAsync(attchmentId);
        }
        
        public void InsertRating(JustStay.ATRC.CommonServiceReference.RatingDto rate) {
            base.Channel.InsertRating(rate);
        }
        
        public System.Threading.Tasks.Task InsertRatingAsync(JustStay.ATRC.CommonServiceReference.RatingDto rate) {
            return base.Channel.InsertRatingAsync(rate);
        }
        
        public JustStay.ATRC.CommonServiceReference.RatingDto[] GetAllRating(int atrcid) {
            return base.Channel.GetAllRating(atrcid);
        }
        
        public System.Threading.Tasks.Task<JustStay.ATRC.CommonServiceReference.RatingDto[]> GetAllRatingAsync(int atrcid) {
            return base.Channel.GetAllRatingAsync(atrcid);
        }
        
        public string Encrypt(string data) {
            return base.Channel.Encrypt(data);
        }
        
        public System.Threading.Tasks.Task<string> EncryptAsync(string data) {
            return base.Channel.EncryptAsync(data);
        }
        
        public string Decrypt(string data) {
            return base.Channel.Decrypt(data);
        }
        
        public System.Threading.Tasks.Task<string> DecryptAsync(string data) {
            return base.Channel.DecryptAsync(data);
        }
    }
}
