//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustStay.Web.ErrorLogServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorLogDto", Namespace="http://schemas.datacontract.org/2004/07/JustStay.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ErrorLogDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eventnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pagenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorFrom {
            get {
                return this.ErrorFromField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorFromField, value) != true)) {
                    this.ErrorFromField = value;
                    this.RaisePropertyChanged("ErrorFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Logid {
            get {
                return this.LogidField;
            }
            set {
                if ((this.LogidField.Equals(value) != true)) {
                    this.LogidField = value;
                    this.RaisePropertyChanged("Logid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eventname {
            get {
                return this.eventnameField;
            }
            set {
                if ((object.ReferenceEquals(this.eventnameField, value) != true)) {
                    this.eventnameField = value;
                    this.RaisePropertyChanged("eventname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pagename {
            get {
                return this.pagenameField;
            }
            set {
                if ((object.ReferenceEquals(this.pagenameField, value) != true)) {
                    this.pagenameField = value;
                    this.RaisePropertyChanged("pagename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ErrorLogServiceReference.IErrorLogService")]
    public interface IErrorLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLogService/InsertErrorLog", ReplyAction="http://tempuri.org/IErrorLogService/InsertErrorLogResponse")]
        void InsertErrorLog(JustStay.Web.ErrorLogServiceReference.ErrorLogDto erroelogDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLogService/InsertErrorLog", ReplyAction="http://tempuri.org/IErrorLogService/InsertErrorLogResponse")]
        System.Threading.Tasks.Task InsertErrorLogAsync(JustStay.Web.ErrorLogServiceReference.ErrorLogDto erroelogDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IErrorLogServiceChannel : JustStay.Web.ErrorLogServiceReference.IErrorLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErrorLogServiceClient : System.ServiceModel.ClientBase<JustStay.Web.ErrorLogServiceReference.IErrorLogService>, JustStay.Web.ErrorLogServiceReference.IErrorLogService {
        
        public ErrorLogServiceClient() {
        }
        
        public ErrorLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErrorLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertErrorLog(JustStay.Web.ErrorLogServiceReference.ErrorLogDto erroelogDto) {
            base.Channel.InsertErrorLog(erroelogDto);
        }
        
        public System.Threading.Tasks.Task InsertErrorLogAsync(JustStay.Web.ErrorLogServiceReference.ErrorLogDto erroelogDto) {
            return base.Channel.InsertErrorLogAsync(erroelogDto);
        }
    }
}
