//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustStay.ATRC.ErrorLogServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ErrorLogServiceReference.IErrorLogService")]
    public interface IErrorLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLogService/InsertErrorLog", ReplyAction="http://tempuri.org/IErrorLogService/InsertErrorLogResponse")]
        void InsertErrorLog(JustStay.CommonHub.ErrorLogServiceReference.ErrorLogDto erroelogDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErrorLogService/InsertErrorLog", ReplyAction="http://tempuri.org/IErrorLogService/InsertErrorLogResponse")]
        System.Threading.Tasks.Task InsertErrorLogAsync(JustStay.CommonHub.ErrorLogServiceReference.ErrorLogDto erroelogDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IErrorLogServiceChannel : JustStay.ATRC.ErrorLogServiceReference.IErrorLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErrorLogServiceClient : System.ServiceModel.ClientBase<JustStay.ATRC.ErrorLogServiceReference.IErrorLogService>, JustStay.ATRC.ErrorLogServiceReference.IErrorLogService {
        
        public ErrorLogServiceClient() {
        }
        
        public ErrorLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErrorLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertErrorLog(JustStay.CommonHub.ErrorLogServiceReference.ErrorLogDto erroelogDto) {
            base.Channel.InsertErrorLog(erroelogDto);
        }
        
        public System.Threading.Tasks.Task InsertErrorLogAsync(JustStay.CommonHub.ErrorLogServiceReference.ErrorLogDto erroelogDto) {
            return base.Channel.InsertErrorLogAsync(erroelogDto);
        }
    }
}
